---
title: "East Boston Demographics"
output: html_document
author: Naomi, Abdul 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
library(leaflet)
library(sf)
library(tidyverse)
library(tidycensus)
library(ggthemes)
library(ggspatial)
library(htmlwidgets)
library(tidytransit)
```

```{r}
vars2010 <- load_variables(2010, "sf1")
```


```{r}
boston_latinx <- get_decennial(geography = "tract",
                          state = "MA", county = "suffolk",
                          year = 2010,
                          output = "wide",
                          variables = c(tot_pop = 'P004001',
                                        la_pop = 'P004003'),
                          geometry = TRUE)

boston_latinx <- boston_latinx %>%
  mutate(pct_latinx = la_pop / tot_pop) %>%
  filter(tot_pop > 0)
```


```{r}
acs_vars <- load_variables(2019, "acs5")
```

```{r}
v19 <- load_variables(2019, "acs5", cache = TRUE)
```

##Latinx Population in East Boston (Interactive) - Census Blocks

```{r}
MA_latinx_palette <- colorNumeric(c("lightpink", "yellow"), boston_latinx$pct_latinx)

latinx_map1 <- leaflet(boston_latinx) %>%
  addProviderTiles("Stamen.TonerLite") %>%
  addPolygons(color = ~MA_latinx_palette(pct_latinx), stroke = FALSE, fillOpacity = 0.7,
              highlightOptions = highlightOptions(fillColor = "orange", fillOpacity = 0.9),
              label = boston_latinx$NAME,
               popup = paste("Total population: ", boston_latinx$tot_pop, "<br/>",
                            "Latinx population: ", boston_latinx$la_pop, " (", 
                            round(boston_latinx$pct_latinx * 100, 1), "%)", sep = "")) %>%
  addLegend("bottomright", pal = MA_latinx_palette, values = ~pct_latinx,
    title = "Percent of population<br/>identifying as Hispanic or Latinx",
    labFormat = labelFormat(suffix = "%",
                            transform = function(x) 100 * x),
    opacity = 1)

latinx_map1
```

##Latinx Population (Static Map)
```{r}
MA_state_plane <- "+proj=lcc +lat_1=42.68333333333333 +lat_2=41.71666666666667 +lat_0=41 +lon_0=-71.5 +x_0=200000.0001016002 +y_0=750000 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs"

ggplot(boston_latinx) +
  annotation_map_tile(zoomin = 0, progress = "none", type = "stamenbw") +
  geom_sf(color = NA, aes(fill = pct_latinx), alpha = 0.7) +
  coord_sf(crs = MA_state_plane) +
  scale_fill_continuous(low="cornsilk", high="darkgreen", 
                       na.value=NA,
                       name = "Percent of population\nidentifying as Latinx",
                       breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1),
                       labels = c("0", "20%", "40%", "60%", "80%", "100%")) +
  theme_void() 
```

```{r}
saveWidget(latinx_map1, file="latinx_map_TRACT.html")
```

##

```{r}
boston_latinx <- get_decennial(geography = "block",
                          state = "MA", county = "suffolk",
                          year = 2010,
                          output = "wide",
                          variables = c(tot_pop = 'P004001',
                                        la_pop = 'P004003'),
                          geometry = TRUE)

boston_latinx <- boston_latinx %>%
  mutate(pct_latinx = la_pop / tot_pop) %>%
  filter(tot_pop > 0)
```

##Latinx Population - Census Blocks
```{r}
MA_latinx_palette <- colorNumeric(c("lightpink", "yellow"), boston_latinx$pct_latinx)

latinx_map_TRACT <- leaflet(boston_latinx) %>%
  addProviderTiles("Stamen.TonerLite") %>%
  addPolygons(color = ~MA_latinx_palette(pct_latinx), stroke = FALSE, fillOpacity = 0.7,
              highlightOptions = highlightOptions(fillColor = "orange", fillOpacity = 0.9),
              label = boston_latinx$NAME,
               popup = paste("Total population: ", boston_latinx$tot_pop, "<br/>",
                            "Latinx population: ", boston_latinx$la_pop, " (", 
                            round(boston_latinx$pct_latinx * 100, 1), "%)", sep = "")) %>%
  addLegend("bottomright", pal = MA_latinx_palette, values = ~pct_latinx,
    title = "Percent of population<br/>identifying as Hispanic or Latinx",
    labFormat = labelFormat(suffix = "%",
                            transform = function(x) 100 * x),
    opacity = 1)

latinx_map_TRACT
```

```{r}
saveWidget(latinx_map_TRACT, file="latinx_map_BLOCK.html")
```


```{r}
medianlatinx_Suffolk <- get_acs(geography = "tract", county = "Suffolk", state = "MA", 
                           year = 2019, survey = "acs5",
                           variables = c(latinx_income = "B19013I_001"),
                           output = "wide", geometry = TRUE) 
```

```{r}
medianlatinx_Suffolk <- medianlatinx_Suffolk %>%
  select(-latinx_incomeM) %>%
  filter(latinx_incomeE > 0)
```


```{r}
income_palette <- colorNumeric(c("purple", "lightblue"),
                                medianlatinx_Suffolk$latinx_incomeE)

medianincome_map <- leaflet(medianlatinx_Suffolk) %>%
  addProviderTiles("Stamen.TonerLite") %>%
  addPolygons(fillColor = ~income_palette(latinx_incomeE), weight = 1, color = "gray", fillOpacity = 0.7,
              highlightOptions = highlightOptions(fillColor = "yellow", fillOpacity = 0.9),
              label = medianlatinx_Suffolk$NAME,
              popup = paste("Median Income: ", medianlatinx_Suffolk$latinx_incomeE, "<br/>")) %>%
    addLegend("bottomright", pal = income_palette, values = ~latinx_incomeE,
    title = "Median Household Income<br/>for Latinx Household",
    labFormat = labelFormat(suffix = "$"),
    opacity = 1)

medianincome_map
```


```{r}
saveWidget(medianincome_map, file="medianincome_map_TRACT.html")
```


```{r}
latinx_pop_Suffolk <- get_acs(geography = "tract", county = "Suffolk", state = "MA", 
                           year = 2019, survey = "acs5",
                           variables = c(tot_pop = "B01003_001", latinx_pop = "B03001_001"),
                           output = "wide", geometry = TRUE) 
```

```{r}
latinx_pop_Suffolk <- latinx_pop_Suffolk %>%
  filter(tot_popE > 0) %>%
  mutate(pct_latinx = round(100 * latinx_popE / tot_popE, 1))
```

```{r}
latinx_pop_palette <- colorNumeric(c("lightpink", "yellow"),
                                latinx_pop_Suffolk$pct_latinx)

latinx_pop_map <- leaflet(latinx_pop_Suffolk) %>%
  addProviderTiles("Stamen.TonerLite") %>%
  addPolygons(fillColor = ~latinx_pop_palette(pct_latinx), weight = 1, color = "gray", fillOpacity = 0.7,
              highlightOptions = highlightOptions(fillColor = "yellow", fillOpacity = 0.9),
              label = latinx_pop_Suffolk$NAME,
              popup = paste("Total workers: ", latinx_pop_Suffolk$tot_popE, "<br/>",
                            "Transit commuters: ", latinx_pop_Suffolk$latinx_popE, " (", 
                            latinx_pop_Suffolk$pct_latinx, "%)", sep = "")) %>%
    addLegend("bottomright", pal = latinx_pop_palette, values = ~pct_latinx,
    title = "Percent of population<br/>identifying as Hispanic/Latinx",
    labFormat = labelFormat(suffix = "%"),
    opacity = 1)

latinx_pop_map
```

